// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lyrics_on_go/domain_layer/album/model/album_track.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'album_model.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'album_model.g.dart';

@freezed
class AlbumModel with _$AlbumModel {
  const factory AlbumModel({
    required String albumCover,
    required AlbumDownloadedState downloadedState,
    required List<AlbumTrack> tracks,
  }) = _AlbumModel;

  factory AlbumModel.fromJson(Map<String, Object?> json) => _$AlbumModelFromJson(json);
}

enum AlbumDownloadedState { downloaded, partly, not }
