// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lyrics_on_go/domain_layer/album/model/album_track.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'album_model_api.freezed.dart';

// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'album_model_api.g.dart';

@freezed
class AlbumModelApi with _$AlbumModelApi {
  const factory AlbumModelApi({
    required String title,
    required String albumCover,
    required List<AlbumTrack> tracks,
  }) = _AlbumModelApi;

  factory AlbumModelApi.fromJson(Map<String, Object?> json) => _$AlbumModelApiFromJson(json);
}
